ALTER TABLE auth_risk_states COMMENT = '';

ALTER TABLE auth_risk_states
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN scene VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN subject_type VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN subject_hash VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN window_started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '',
	MODIFY COLUMN attempt_count INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN failed_count INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN captcha_failed_count INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN lock_until DATETIME(6) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '';

ALTER TABLE auth_captcha_challenges COMMENT = '';

ALTER TABLE auth_captcha_challenges
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN captcha_id VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN scene VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN subject_hash VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN level INT NOT NULL DEFAULT 4 COMMENT '',
	MODIFY COLUMN answer_hash VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN answer_salt VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN issued_ip_hash VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN expires_at DATETIME(6) NOT NULL COMMENT '',
	MODIFY COLUMN consumed_at DATETIME(6) NULL COMMENT '',
	MODIFY COLUMN failed_verify_count INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '';
