ALTER TABLE users COMMENT = '';
ALTER TABLE users
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN email VARCHAR(320) NOT NULL COMMENT '',
	MODIFY COLUMN password_hash TEXT NOT NULL COMMENT '',
	MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN avatar_url VARCHAR(512) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '',
	MODIFY COLUMN banned_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN banned_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE spaces COMMENT = '';
ALTER TABLE spaces
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '',
	MODIFY COLUMN owner_user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN description VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN category VARCHAR(120) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN category_id VARCHAR(26) NOT NULL DEFAULT '01jmf4v2x7m7f1m6qv5kh0t2mn' COMMENT '',
	MODIFY COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'member' COMMENT '',
	MODIFY COLUMN cover_asset_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN cover_key VARCHAR(512) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN cover_url TEXT NOT NULL COMMENT '',
	MODIFY COLUMN cover_width INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN cover_height INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN cover_source VARCHAR(32) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '',
	MODIFY COLUMN banned_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN banned_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE space_members COMMENT = '';
ALTER TABLE space_members
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE nodes COMMENT = '';
ALTER TABLE nodes
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN node_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN parent_node_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN type VARCHAR(16) NOT NULL COMMENT '',
	MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '',
	MODIFY COLUMN sort INT NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN created_by_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN updated_by_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE themes COMMENT = '';
ALTER TABLE themes
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN theme_id VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN description TEXT NOT NULL COMMENT '',
	MODIFY COLUMN variables_json MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN syntax_theme VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN code_block_style_json MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN code_block_code_style_json MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN inline_code_style_json MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN custom_css MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN is_builtin TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN is_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE documents COMMENT = '';
ALTER TABLE documents
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN document_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN node_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN theme_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '',
	MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '',
	MODIFY COLUMN content_md MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN version INT NOT NULL DEFAULT 1 COMMENT '',
	MODIFY COLUMN created_by_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN updated_by_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'member' COMMENT '',
	MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '',
	MODIFY COLUMN banned_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN banned_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE document_revisions COMMENT = '';
ALTER TABLE document_revisions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN document_revision_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN document_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN version INT NOT NULL COMMENT '',
	MODIFY COLUMN content_md MEDIUMTEXT NOT NULL COMMENT '',
	MODIFY COLUMN base_version INT NOT NULL COMMENT '',
	MODIFY COLUMN editor_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN source VARCHAR(16) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE node_permissions COMMENT = '';
ALTER TABLE node_permissions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN node_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '',
	MODIFY COLUMN granted_by_user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE document_permissions COMMENT = '';
ALTER TABLE document_permissions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN document_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '',
	MODIFY COLUMN granted_by_user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE user_sessions COMMENT = '';
ALTER TABLE user_sessions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN session_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN refresh_token_hash VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN expires_at DATETIME(3) NOT NULL COMMENT '',
	MODIFY COLUMN revoked_at DATETIME(3) NULL COMMENT '',
	MODIFY COLUMN replaced_by_session_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '';

ALTER TABLE user_admin_roles COMMENT = '';
ALTER TABLE user_admin_roles
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN role VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '';

ALTER TABLE space_admin_scopes COMMENT = '';
ALTER TABLE space_admin_scopes
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '';

ALTER TABLE system_configs COMMENT = '';
ALTER TABLE system_configs
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '',
	MODIFY COLUMN config_value_json LONGTEXT NOT NULL COMMENT '',
	MODIFY COLUMN version INT NOT NULL DEFAULT 1 COMMENT '',
	MODIFY COLUMN updated_by_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '';

ALTER TABLE audit_logs COMMENT = '';
ALTER TABLE audit_logs
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN actor_user_id VARCHAR(26) NULL COMMENT '',
	MODIFY COLUMN module VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN target_type VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN target_id VARCHAR(191) NOT NULL COMMENT '',
	MODIFY COLUMN summary TEXT NOT NULL COMMENT '',
	MODIFY COLUMN detail_json LONGTEXT NOT NULL COMMENT '',
	MODIFY COLUMN request_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '';

ALTER TABLE space_cover_assets COMMENT = '';
ALTER TABLE space_cover_assets
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN asset_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN source VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN object_key VARCHAR(512) NOT NULL COMMENT '',
	MODIFY COLUMN object_url TEXT NOT NULL COMMENT '',
	MODIFY COLUMN mime_type VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN width INT NOT NULL COMMENT '',
	MODIFY COLUMN height INT NOT NULL COMMENT '',
	MODIFY COLUMN size_bytes BIGINT NOT NULL COMMENT '',
	MODIFY COLUMN normalized TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
	MODIFY COLUMN created_by_user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '';

ALTER TABLE space_categories COMMENT = '';
ALTER TABLE space_categories
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN category_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN name VARCHAR(120) NOT NULL COMMENT '',
	MODIFY COLUMN is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE user_identities COMMENT = '';
ALTER TABLE user_identities
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '',
	MODIFY COLUMN provider_type VARCHAR(32) NOT NULL COMMENT '',
	MODIFY COLUMN provider_id VARCHAR(64) NOT NULL COMMENT '',
	MODIFY COLUMN external_id VARCHAR(255) NOT NULL COMMENT '',
	MODIFY COLUMN login_name VARCHAR(320) NOT NULL DEFAULT '' COMMENT '',
	MODIFY COLUMN last_login_at DATETIME NULL COMMENT '',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';
