ALTER TABLE users COMMENT = '用户主表：存储账号基础信息与用户状态';
ALTER TABLE users
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '用户业务ID（ULID）',
	MODIFY COLUMN email VARCHAR(320) NOT NULL COMMENT '用户邮箱（全局唯一）',
	MODIFY COLUMN password_hash TEXT NOT NULL COMMENT '密码哈希（bcrypt）',
	MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '用户显示名称',
	MODIFY COLUMN avatar_url VARCHAR(512) NOT NULL DEFAULT '' COMMENT '头像URL',
	MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '用户状态：active/banned/deleted',
	MODIFY COLUMN banned_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '封禁原因',
	MODIFY COLUMN banned_at DATETIME(3) NULL COMMENT '封禁时间',
	MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '逻辑删除时间',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE spaces COMMENT = '知识空间表：协作内容的顶层容器';
ALTER TABLE spaces
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '空间业务ID（ULID）',
	MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '空间名称',
	MODIFY COLUMN owner_user_id VARCHAR(26) NOT NULL COMMENT '空间所有者用户ID',
	MODIFY COLUMN description VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '空间描述',
	MODIFY COLUMN category VARCHAR(120) NOT NULL DEFAULT '' COMMENT '空间分类名称（兼容旧字段）',
	MODIFY COLUMN category_id VARCHAR(26) NOT NULL DEFAULT '01jmf4v2x7m7f1m6qv5kh0t2mn' COMMENT '空间分类ID（关联 space_categories.category_id）',
	MODIFY COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'member' COMMENT '空间可见性：public/authenticated/member',
	MODIFY COLUMN cover_asset_id VARCHAR(26) NULL COMMENT '封面素材ID（关联 space_cover_assets.asset_id）',
	MODIFY COLUMN cover_key VARCHAR(512) NOT NULL DEFAULT '' COMMENT '封面对象存储键',
	MODIFY COLUMN cover_url TEXT NOT NULL COMMENT '封面访问URL',
	MODIFY COLUMN cover_width INT NOT NULL DEFAULT 0 COMMENT '封面宽度（像素）',
	MODIFY COLUMN cover_height INT NOT NULL DEFAULT 0 COMMENT '封面高度（像素）',
	MODIFY COLUMN cover_source VARCHAR(32) NOT NULL DEFAULT '' COMMENT '封面来源：空/用户上传/系统生成',
	MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '空间状态：active/banned/deleted',
	MODIFY COLUMN banned_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '空间封禁原因',
	MODIFY COLUMN banned_at DATETIME(3) NULL COMMENT '空间封禁时间',
	MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '空间逻辑删除时间',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE space_members COMMENT = '空间成员关系表：定义用户在空间中的协作角色';
ALTER TABLE space_members
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '空间业务ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '用户业务ID',
	MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '空间角色：owner/collaborator/reader',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE nodes COMMENT = '目录树节点表：空间内目录与文档节点';
ALTER TABLE nodes
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN node_id VARCHAR(26) NOT NULL COMMENT '节点业务ID（ULID）',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '所属空间ID',
	MODIFY COLUMN parent_node_id VARCHAR(26) NULL COMMENT '父节点ID，空表示根节点',
	MODIFY COLUMN type VARCHAR(16) NOT NULL COMMENT '节点类型：folder/doc',
	MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '节点标题',
	MODIFY COLUMN sort INT NOT NULL DEFAULT 0 COMMENT '同级排序值',
	MODIFY COLUMN created_by_user_id VARCHAR(26) NULL COMMENT '节点创建人用户ID',
	MODIFY COLUMN updated_by_user_id VARCHAR(26) NULL COMMENT '节点最后更新人用户ID',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE themes COMMENT = '文档主题表：存储主题样式与代码高亮配置';
ALTER TABLE themes
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN theme_id VARCHAR(64) NOT NULL COMMENT '主题业务ID',
	MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '主题名称',
	MODIFY COLUMN description TEXT NOT NULL COMMENT '主题描述',
	MODIFY COLUMN variables_json MEDIUMTEXT NOT NULL COMMENT 'CSS 变量JSON',
	MODIFY COLUMN syntax_theme VARCHAR(32) NOT NULL COMMENT '代码高亮主题：one-light/one-dark',
	MODIFY COLUMN code_block_style_json MEDIUMTEXT NOT NULL COMMENT '代码块容器样式JSON',
	MODIFY COLUMN code_block_code_style_json MEDIUMTEXT NOT NULL COMMENT '代码块代码样式JSON',
	MODIFY COLUMN inline_code_style_json MEDIUMTEXT NOT NULL COMMENT '行内代码样式JSON',
	MODIFY COLUMN custom_css MEDIUMTEXT NOT NULL COMMENT '自定义CSS',
	MODIFY COLUMN is_builtin TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否内置主题',
	MODIFY COLUMN is_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE documents COMMENT = '文档主表：节点对应的正文与可见性状态';
ALTER TABLE documents
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN document_id VARCHAR(26) NOT NULL COMMENT '文档业务ID（ULID）',
	MODIFY COLUMN node_id VARCHAR(26) NOT NULL COMMENT '关联节点ID（唯一）',
	MODIFY COLUMN theme_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '主题ID',
	MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '文档标题',
	MODIFY COLUMN content_md MEDIUMTEXT NOT NULL COMMENT 'Markdown 正文',
	MODIFY COLUMN version INT NOT NULL DEFAULT 1 COMMENT '文档版本号（乐观锁）',
	MODIFY COLUMN created_by_user_id VARCHAR(26) NULL COMMENT '文档创建人用户ID',
	MODIFY COLUMN updated_by_user_id VARCHAR(26) NULL COMMENT '最后更新人用户ID',
	MODIFY COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'member' COMMENT '文档可见性：public/authenticated/member',
	MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '文档状态：active/banned/deleted',
	MODIFY COLUMN banned_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '文档封禁原因',
	MODIFY COLUMN banned_at DATETIME(3) NULL COMMENT '文档封禁时间',
	MODIFY COLUMN deleted_at DATETIME(3) NULL COMMENT '文档逻辑删除时间',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE document_revisions COMMENT = '文档修订历史表：保存版本快照与来源';
ALTER TABLE document_revisions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN document_revision_id VARCHAR(26) NOT NULL COMMENT '修订业务ID（ULID）',
	MODIFY COLUMN document_id VARCHAR(26) NOT NULL COMMENT '文档业务ID',
	MODIFY COLUMN version INT NOT NULL COMMENT '修订版本号',
	MODIFY COLUMN content_md MEDIUMTEXT NOT NULL COMMENT '该版本 Markdown 内容',
	MODIFY COLUMN base_version INT NOT NULL COMMENT '保存时基准版本号',
	MODIFY COLUMN editor_user_id VARCHAR(26) NULL COMMENT '编辑人用户ID',
	MODIFY COLUMN source VARCHAR(16) NOT NULL COMMENT '修订来源：local/remote',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE node_permissions COMMENT = '节点权限表：节点级 ACL 授权关系';
ALTER TABLE node_permissions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN node_id VARCHAR(26) NOT NULL COMMENT '节点业务ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '被授权用户ID',
	MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '授权角色：owner/collaborator/reader',
	MODIFY COLUMN granted_by_user_id VARCHAR(26) NOT NULL COMMENT '授权人用户ID',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE document_permissions COMMENT = '文档权限表：文档级 ACL 授权关系';
ALTER TABLE document_permissions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN document_id VARCHAR(26) NOT NULL COMMENT '文档业务ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '被授权用户ID',
	MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '授权角色：owner/collaborator/reader',
	MODIFY COLUMN granted_by_user_id VARCHAR(26) NOT NULL COMMENT '授权人用户ID',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_sessions COMMENT = '用户会话表：refresh token 会话状态与轮换链';
ALTER TABLE user_sessions
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN session_id VARCHAR(26) NOT NULL COMMENT '会话业务ID（ULID）',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '用户业务ID',
	MODIFY COLUMN refresh_token_hash VARCHAR(64) NOT NULL COMMENT 'refresh token 哈希',
	MODIFY COLUMN expires_at DATETIME(3) NOT NULL COMMENT '会话过期时间',
	MODIFY COLUMN revoked_at DATETIME(3) NULL COMMENT '会话吊销时间',
	MODIFY COLUMN replaced_by_session_id VARCHAR(26) NULL COMMENT '被旋转后替换的新会话ID',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE user_admin_roles COMMENT = '管理员角色表：绑定平台级管理员角色';
ALTER TABLE user_admin_roles
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '用户业务ID',
	MODIFY COLUMN role VARCHAR(32) NOT NULL COMMENT '管理员角色：platform_admin/space_admin',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE space_admin_scopes COMMENT = '空间管理员范围表：约束 space_admin 可管理的空间';
ALTER TABLE space_admin_scopes
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '管理员用户ID',
	MODIFY COLUMN space_id VARCHAR(26) NOT NULL COMMENT '可管理空间ID',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE system_configs COMMENT = '系统配置中心表：按 config_key 存储 JSON 配置与版本';
ALTER TABLE system_configs
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '配置键（唯一）',
	MODIFY COLUMN config_value_json LONGTEXT NOT NULL COMMENT '配置值JSON',
	MODIFY COLUMN version INT NOT NULL DEFAULT 1 COMMENT '配置版本号（从 1 递增）',
	MODIFY COLUMN updated_by_user_id VARCHAR(26) NULL COMMENT '最后更新人用户ID',
	MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '更新时间';

ALTER TABLE audit_logs COMMENT = '后台审计日志表：记录管理端关键操作轨迹';
ALTER TABLE audit_logs
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN actor_user_id VARCHAR(26) NULL COMMENT '操作者用户ID',
	MODIFY COLUMN module VARCHAR(64) NOT NULL COMMENT '操作模块',
	MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '操作动作',
	MODIFY COLUMN target_type VARCHAR(64) NOT NULL COMMENT '目标资源类型',
	MODIFY COLUMN target_id VARCHAR(191) NOT NULL COMMENT '目标资源ID',
	MODIFY COLUMN summary TEXT NOT NULL COMMENT '操作摘要',
	MODIFY COLUMN detail_json LONGTEXT NOT NULL COMMENT '操作详情JSON',
	MODIFY COLUMN request_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '请求链路ID',
	MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间';

ALTER TABLE space_cover_assets COMMENT = '空间封面素材表：记录封面源文件元数据';
ALTER TABLE space_cover_assets
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN asset_id VARCHAR(26) NOT NULL COMMENT '素材业务ID（ULID）',
	MODIFY COLUMN source VARCHAR(32) NOT NULL COMMENT '素材来源：user_upload/system_generated',
	MODIFY COLUMN object_key VARCHAR(512) NOT NULL COMMENT '对象存储键',
	MODIFY COLUMN object_url TEXT NOT NULL COMMENT '对象访问URL',
	MODIFY COLUMN mime_type VARCHAR(64) NOT NULL COMMENT '文件MIME类型',
	MODIFY COLUMN width INT NOT NULL COMMENT '图片宽度（像素）',
	MODIFY COLUMN height INT NOT NULL COMMENT '图片高度（像素）',
	MODIFY COLUMN size_bytes BIGINT NOT NULL COMMENT '文件字节大小',
	MODIFY COLUMN normalized TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否已完成尺寸与格式归一化',
	MODIFY COLUMN created_by_user_id VARCHAR(26) NOT NULL COMMENT '创建人用户ID',
	MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE space_categories COMMENT = '空间分类表：管理空间归类维度';
ALTER TABLE space_categories
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN category_id VARCHAR(26) NOT NULL COMMENT '分类业务ID（ULID）',
	MODIFY COLUMN name VARCHAR(120) NOT NULL COMMENT '分类名称',
	MODIFY COLUMN is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认分类',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_identities COMMENT = '用户身份映射表：关联本地账号与外部身份提供方';
ALTER TABLE user_identities
	MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	MODIFY COLUMN user_id VARCHAR(26) NOT NULL COMMENT '用户业务ID',
	MODIFY COLUMN provider_type VARCHAR(32) NOT NULL COMMENT '身份提供方类型，如 local/ldap',
	MODIFY COLUMN provider_id VARCHAR(64) NOT NULL COMMENT '身份提供方实例ID',
	MODIFY COLUMN external_id VARCHAR(255) NOT NULL COMMENT '外部身份唯一标识',
	MODIFY COLUMN login_name VARCHAR(320) NOT NULL DEFAULT '' COMMENT '用于登录展示或匹配的名称',
	MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最近一次登录时间',
	MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
