ALTER TABLE schema_migrations COMMENT = '';

ALTER TABLE schema_migrations
	MODIFY COLUMN version BIGINT NOT NULL COMMENT '',
	MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '',
	MODIFY COLUMN applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '';
