CREATE TABLE IF NOT EXISTS document_attachments (
	id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
	attachment_id VARCHAR(26) NOT NULL COMMENT '附件业务ID（ULID）',
	document_id VARCHAR(26) NOT NULL COMMENT '文档业务ID',
	space_id VARCHAR(26) NOT NULL COMMENT '所属空间ID',
	storage_provider VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT '存储提供方：local/cloudflare-r2/aliyun-oss',
	file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
	object_key VARCHAR(512) NOT NULL DEFAULT '' COMMENT '对象键',
	object_url TEXT NOT NULL COMMENT '对象访问URL',
	mime_type VARCHAR(128) NOT NULL DEFAULT 'application/octet-stream' COMMENT 'MIME 类型',
	size_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '文件字节数',
	preview_kind VARCHAR(32) NOT NULL DEFAULT 'none' COMMENT '在线预览类型扩展：none/image/pdf/office/text',
	status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '附件状态：active/deleted',
	deleted_at DATETIME(3) NULL COMMENT '逻辑删除时间',
	created_by_user_id VARCHAR(26) NULL COMMENT '创建人用户ID',
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
	UNIQUE KEY uk_document_attachments_attachment_id (attachment_id),
	KEY idx_document_attachments_document_id (document_id),
	KEY idx_document_attachments_space_id (space_id),
	KEY idx_document_attachments_status (status),
	KEY idx_document_attachments_created_at (created_at),
	CONSTRAINT fk_document_attachments_document_id FOREIGN KEY (document_id) REFERENCES documents(document_id) ON DELETE CASCADE,
	CONSTRAINT fk_document_attachments_space_id FOREIGN KEY (space_id) REFERENCES spaces(space_id) ON DELETE CASCADE,
	CONSTRAINT fk_document_attachments_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档附件表：记录文档关联文件与存储元信息';
