CREATE TABLE IF NOT EXISTS document_templates (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	template_id VARCHAR(64) NOT NULL,
	scene_key VARCHAR(64) NOT NULL,
	scene_name VARCHAR(80) NOT NULL,
	name VARCHAR(120) NOT NULL,
	description VARCHAR(255) NOT NULL DEFAULT '',
	default_title VARCHAR(120) NOT NULL DEFAULT '',
	content_md MEDIUMTEXT NOT NULL,
	sort INT NOT NULL DEFAULT 0,
	is_builtin TINYINT(1) NOT NULL DEFAULT 0,
	is_enabled TINYINT(1) NOT NULL DEFAULT 1,
	created_by_user_id VARCHAR(26) NULL,
	updated_by_user_id VARCHAR(26) NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (id),
	UNIQUE KEY uk_document_templates_template_id (template_id),
	KEY idx_document_templates_scene_enabled_sort_updated_at (scene_key, is_enabled, sort, updated_at),
	KEY idx_document_templates_enabled_updated_at (is_enabled, updated_at),
	CONSTRAINT fk_document_templates_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL,
	CONSTRAINT fk_document_templates_updated_by_user_id FOREIGN KEY (updated_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档模板表：存储模板内容与启用状态';
