CREATE TABLE IF NOT EXISTS document_shares (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	share_id VARCHAR(26) NOT NULL,
	document_id VARCHAR(26) NOT NULL,
	space_id VARCHAR(26) NOT NULL,
	mode VARCHAR(16) NOT NULL DEFAULT 'public',
	password_hash TEXT NULL,
	password_hint VARCHAR(120) NOT NULL DEFAULT '',
	expires_at DATETIME(3) NULL,
	disabled_at DATETIME(3) NULL,
	access_version INT NOT NULL DEFAULT 1,
	created_by_user_id VARCHAR(26) NULL,
	updated_by_user_id VARCHAR(26) NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (id),
	UNIQUE KEY uk_document_shares_share_id (share_id),
	UNIQUE KEY uk_document_shares_document_id (document_id),
	KEY idx_document_shares_space_disabled_expires (space_id, disabled_at, expires_at),
	KEY idx_document_shares_mode (mode),
	KEY idx_document_shares_created_by_user_id (created_by_user_id),
	CONSTRAINT ck_document_shares_mode CHECK (mode IN ('public', 'password')),
	CONSTRAINT ck_document_shares_access_version CHECK (access_version > 0),
	CONSTRAINT fk_document_shares_document_id FOREIGN KEY (document_id) REFERENCES documents(document_id) ON DELETE CASCADE,
	CONSTRAINT fk_document_shares_space_id FOREIGN KEY (space_id) REFERENCES spaces(space_id) ON DELETE CASCADE,
	CONSTRAINT fk_document_shares_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL,
	CONSTRAINT fk_document_shares_updated_by_user_id FOREIGN KEY (updated_by_user_id) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档分享表：记录分享方式、有效期与访问版本';
