CREATE TABLE IF NOT EXISTS admin_space_transfer_jobs (
	id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
	job_id VARCHAR(26) NOT NULL COMMENT '任务业务ID（ULID）',
	kind VARCHAR(32) NOT NULL COMMENT '任务类型：space_export/space_import',
	actor_user_id VARCHAR(64) NOT NULL COMMENT '任务发起用户ID',
	space_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '空间ID',
	space_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '空间名称快照',
	format VARCHAR(32) NOT NULL DEFAULT '' COMMENT '导出格式',
	import_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '导入 staging ID',
	status VARCHAR(16) NOT NULL DEFAULT 'queued' COMMENT '任务状态：queued/running/completed/failed',
	stage VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前阶段',
	progress INT NOT NULL DEFAULT 0 COMMENT '进度百分比',
	message TEXT NOT NULL COMMENT '用户可见消息',
	file_path TEXT NOT NULL COMMENT '服务端私有文件路径',
	file_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '下载文件名',
	size_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小',
	new_space_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '导入生成的新空间ID',
	error_message TEXT NOT NULL COMMENT '失败错误摘要',
	started_at DATETIME(3) NULL COMMENT '任务开始时间',
	completed_at DATETIME(3) NULL COMMENT '任务终止时间',
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
	expires_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '任务过期时间',
	UNIQUE KEY uk_admin_space_transfer_jobs_job_id (job_id),
	KEY idx_admin_space_transfer_jobs_actor_status_updated (actor_user_id, status, updated_at, id),
	KEY idx_admin_space_transfer_jobs_status_expires (status, expires_at, id),
	KEY idx_admin_space_transfer_jobs_kind_job (kind, job_id),
	CONSTRAINT chk_admin_space_transfer_jobs_kind CHECK (kind IN ('space_export', 'space_import')),
	CONSTRAINT chk_admin_space_transfer_jobs_status CHECK (status IN ('queued', 'running', 'completed', 'failed')),
	CONSTRAINT chk_admin_space_transfer_jobs_progress CHECK (progress >= 0 AND progress <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台空间导入导出任务表';
