import type { Theme } from "./data-access/types";

// 历史内置主题预设：local/http 两种数据驱动统一复用。
export const BUILTIN_THEME_PRESETS: Theme[] = [
  {
    "id": "default",
    "name": "内置默认",
    "description": "通用文档风格",
    "variables": {
      "--pd-preview-padding": "30px",
      "--pd-preview-font-family": "Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "rgb(89, 89, 89)",
      "--pd-preview-link-color": "rgb(71, 193, 168)",
      "--pd-preview-inline-code-color": "rgb(71, 193, 168)",
      "--pd-preview-font-size": "16px",
      "--pd-preview-line-height": "26px",
      "--pd-preview-word-spacing": "3px",
      "--pd-preview-letter-spacing": "0.02em",
      "--pd-preview-paragraph-margin-top": "5px",
      "--pd-preview-paragraph-margin-bottom": "5px",
      "--pd-preview-paragraph-indent": "0.8em",
      "--pd-preview-title-color": "rgb(89, 89, 89)",
      "--pd-preview-h1-font-size": "2em",
      "--pd-preview-h2-font-size": "1.5em",
      "--pd-preview-h3-font-size": "1.25em",
      "--pd-preview-h4-font-size": "1.05em",
      "--pd-preview-h5-font-size": "0.95em",
      "--pd-preview-h6-font-size": "0.88em",
      "--pd-preview-h1-color": "rgb(89, 89, 89)",
      "--pd-preview-h2-color": "rgb(89, 89, 89)",
      "--pd-preview-h3-color": "rgb(89, 89, 89)",
      "--pd-preview-h4-color": "rgb(89, 89, 89)",
      "--pd-preview-h5-color": "rgb(89, 89, 89)",
      "--pd-preview-h6-color": "rgb(89, 89, 89)",
      "--pd-preview-h1-border-width": "0",
      "--pd-preview-h2-border-width": "2px",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "transparent",
      "--pd-preview-h2-border-color": "rgb(89, 89, 89)",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "#666666",
      "--pd-preview-blockquote-mark-color": "#555555",
      "--pd-preview-blockquote-background": "#f8fafc",
      "--pd-preview-blockquote-border-color": "#cbd5e1",
      "--pd-preview-strong-color": "rgb(71, 193, 168)",
      "--pd-preview-em-color": "rgb(71, 193, 168)",
      "--pd-preview-hr-color": "#cbd5e1",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "14px",
      "--pd-preview-table-border-color": "#dbe2ea",
      "--pd-preview-table-cell-padding": "10px 12px"
    },
    "syntaxTheme": "one-light",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "10px",
      "border": "1px solid #dbe2ea",
      "boxShadow": "0 1px 2px rgba(15, 23, 42, 0.06)",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#f8fafc"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "inlineCodeStyle": {
      "padding": "1px 6px",
      "borderRadius": "5px",
      "border": "1px solid #dbe2ea",
      "background": "#f1f5f9",
      "color": "#0f172a",
      "fontSize": "0.92em",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "customCss": "",
    "builtin": true
  },
  {
    "id": "newspaper",
    "name": "报刊主题",
    "description": "更适合长文阅读",
    "variables": {
      "--pd-preview-padding": "34px",
      "--pd-preview-font-family": "Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "#334155",
      "--pd-preview-link-color": "#0f766e",
      "--pd-preview-inline-code-color": "#0f766e",
      "--pd-preview-font-size": "16px",
      "--pd-preview-line-height": "30px",
      "--pd-preview-word-spacing": "1px",
      "--pd-preview-letter-spacing": "0.01em",
      "--pd-preview-paragraph-margin-top": "8px",
      "--pd-preview-paragraph-margin-bottom": "8px",
      "--pd-preview-paragraph-indent": "0.8em",
      "--pd-preview-title-color": "rgb(89,89,89)",
      "--pd-preview-h1-font-size": "2.15em",
      "--pd-preview-h2-font-size": "1.7em",
      "--pd-preview-h3-font-size": "1.35em",
      "--pd-preview-h4-font-size": "1.15em",
      "--pd-preview-h5-font-size": "1em",
      "--pd-preview-h6-font-size": "0.92em",
      "--pd-preview-h1-color": "rgb(89,89,89)",
      "--pd-preview-h2-color": "rgb(89,89,89)",
      "--pd-preview-h3-color": "rgb(89,89,89)",
      "--pd-preview-h4-color": "rgb(89,89,89)",
      "--pd-preview-h5-color": "rgb(89,89,89)",
      "--pd-preview-h6-color": "rgb(89,89,89)",
      "--pd-preview-h1-border-width": "0",
      "--pd-preview-h2-border-width": "2px",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "transparent",
      "--pd-preview-h2-border-color": "#334155",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "#475569",
      "--pd-preview-blockquote-mark-color": "#334155",
      "--pd-preview-blockquote-background": "#f8fafc",
      "--pd-preview-blockquote-border-color": "#94a3b8",
      "--pd-preview-strong-color": "#0f766e",
      "--pd-preview-em-color": "#0f766e",
      "--pd-preview-hr-color": "#94a3b8",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "14px",
      "--pd-preview-table-border-color": "#cbd5e1",
      "--pd-preview-table-cell-padding": "10px 12px"
    },
    "syntaxTheme": "one-light",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "8px",
      "border": "1px solid #cbd5e1",
      "boxShadow": "0 1px 2px rgba(15, 23, 42, 0.06)",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#f8fafc"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Source Code Pro\", \"SFMono-Regular\", Menlo, Monaco, Consolas, monospace"
    },
    "inlineCodeStyle": {
      "padding": "1px 6px",
      "borderRadius": "5px",
      "border": "1px solid #99f6e4",
      "background": "#ecfeff",
      "color": "#115e59",
      "fontSize": "0.92em",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "customCss": "",
    "builtin": true
  },
  {
    "id": "clean-tech",
    "name": "清爽技术",
    "description": "偏开发文档排版",
    "variables": {
      "--pd-preview-padding": "26px",
      "--pd-preview-font-family": "Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "#334155",
      "--pd-preview-link-color": "#0ea5e9",
      "--pd-preview-inline-code-color": "#0284c7",
      "--pd-preview-font-size": "16px",
      "--pd-preview-line-height": "24px",
      "--pd-preview-word-spacing": "0",
      "--pd-preview-letter-spacing": "0",
      "--pd-preview-paragraph-margin-top": "6px",
      "--pd-preview-paragraph-margin-bottom": "6px",
      "--pd-preview-paragraph-indent": "0",
      "--pd-preview-title-color": "rgb(89,89,89)",
      "--pd-preview-h1-font-size": "2.0em",
      "--pd-preview-h2-font-size": "1.65em",
      "--pd-preview-h3-font-size": "1.4em",
      "--pd-preview-h4-font-size": "1.25em",
      "--pd-preview-h5-font-size": "1.15em",
      "--pd-preview-h6-font-size": ".08em",
      "--pd-preview-h1-color": "rgb(89,89,89)",
      "--pd-preview-h2-color": "rgb(89,89,89)",
      "--pd-preview-h3-color": "rgb(89,89,89)",
      "--pd-preview-h4-color": "rgb(89,89,89)",
      "--pd-preview-h5-color": "rgb(89,89,89)",
      "--pd-preview-h6-color": "rgb(89,89,89)",
      "--pd-preview-h1-border-width": "0",
      "--pd-preview-h2-border-width": "2px",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "transparent",
      "--pd-preview-h2-border-color": "#475569",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "#475569",
      "--pd-preview-blockquote-mark-color": "#64748b",
      "--pd-preview-blockquote-background": "#f1f5f9",
      "--pd-preview-blockquote-border-color": "#cbd5e1",
      "--pd-preview-strong-color": "#0369a1",
      "--pd-preview-em-color": "#0284c7",
      "--pd-preview-hr-color": "#cbd5e1",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "13px",
      "--pd-preview-table-border-color": "#cbd5e1",
      "--pd-preview-table-cell-padding": "8px 10px"
    },
    "syntaxTheme": "one-dark",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "12px",
      "border": "1px solid #1e293b",
      "boxShadow": "0 8px 18px rgba(2, 6, 23, 0.2)",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#0f172a"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      "color": "#dbeafe"
    },
    "inlineCodeStyle": {
      "padding": "1px 6px",
      "borderRadius": "6px",
      "border": "none",
      "background": "#e9eef6",
      "color": "#444746",
      "fontSize": "0.92em",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "customCss": "",
    "builtin": true
  },
  {
    "id": "wechat-minimal",
    "name": "微信风格",
    "description": "适合微信公众号极简风",
    "variables": {
      "--pd-preview-padding": "30px",
      "--pd-preview-font-family": "Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "#3f3f3f",
      "--pd-preview-link-color": "#ff3502",
      "--pd-preview-inline-code-color": "#ff3502",
      "--pd-preview-font-size": "16px",
      "--pd-preview-line-height": "26px",
      "--pd-preview-word-spacing": "3px",
      "--pd-preview-letter-spacing": "0",
      "--pd-preview-paragraph-margin-top": "10px",
      "--pd-preview-paragraph-margin-bottom": "10px",
      "--pd-preview-paragraph-indent": "0",
      "--pd-preview-title-color": "#3f3f3f",
      "--pd-preview-h1-font-size": "2em",
      "--pd-preview-h2-font-size": "1.4em",
      "--pd-preview-h3-font-size": "1.2em",
      "--pd-preview-h4-font-size": "1.05em",
      "--pd-preview-h5-font-size": "0.95em",
      "--pd-preview-h6-font-size": "0.88em",
      "--pd-preview-h1-color": "#3f3f3f",
      "--pd-preview-h2-color": "#3f3f3f",
      "--pd-preview-h3-color": "#3f3f3f",
      "--pd-preview-h4-color": "#3f3f3f",
      "--pd-preview-h5-color": "#3f3f3f",
      "--pd-preview-h6-color": "#3f3f3f",
      "--pd-preview-h1-border-width": "0",
      "--pd-preview-h2-border-width": "0",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "transparent",
      "--pd-preview-h2-border-color": "transparent",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "rgb(91,91,91)",
      "--pd-preview-blockquote-mark-color": "transparent",
      "--pd-preview-blockquote-background": "rgba(158, 158, 158, 0.1)",
      "--pd-preview-blockquote-border-color": "rgb(158,158,158)",
      "--pd-preview-strong-color": "#ff3502",
      "--pd-preview-em-color": "#3f3f3f",
      "--pd-preview-hr-color": "#d4d4d4",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "14px",
      "--pd-preview-table-border-color": "#d9d9d9",
      "--pd-preview-table-cell-padding": "8px 10px"
    },
    "syntaxTheme": "one-light",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "6px",
      "border": "1px solid #ececec",
      "boxShadow": "none",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#f8f5ec",
      "color": "#3f3f3f"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      "color": "#3f3f3f"
    },
    "inlineCodeStyle": {
      "padding": "3px 5px",
      "borderRadius": "2px",
      "border": "none",
      "background": "#f8f5ec",
      "color": "#ff3502",
      "fontSize": "90%",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      "lineHeight": 1.5
    },
    "customCss": "",
    "builtin": true
  },
  {
    "id": "green-fresh",
    "name": "绿意清新",
    "description": "轻盈绿色排版风格",
    "variables": {
      "--pd-preview-padding": "30px",
      "--pd-preview-font-family": "Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "#595959",
      "--pd-preview-link-color": "#35b378",
      "--pd-preview-inline-code-color": "#35b378",
      "--pd-preview-font-size": "15px",
      "--pd-preview-line-height": "26px",
      "--pd-preview-word-spacing": "3px",
      "--pd-preview-letter-spacing": "0.05em",
      "--pd-preview-paragraph-margin-top": "1em",
      "--pd-preview-paragraph-margin-bottom": "1em",
      "--pd-preview-paragraph-indent": "0.8em",
      "--pd-preview-title-color": "#35b378",
      "--pd-preview-h1-font-size": "2em",
      "--pd-preview-h2-font-size": "23px",
      "--pd-preview-h3-font-size": "1.25em",
      "--pd-preview-h4-font-size": "1.05em",
      "--pd-preview-h5-font-size": "0.95em",
      "--pd-preview-h6-font-size": "0.88em",
      "--pd-preview-h1-color": "#35b378",
      "--pd-preview-h2-color": "#35b378",
      "--pd-preview-h3-color": "#35b378",
      "--pd-preview-h4-color": "#595959",
      "--pd-preview-h5-color": "#595959",
      "--pd-preview-h6-color": "#595959",
      "--pd-preview-h1-border-width": "0",
      "--pd-preview-h2-border-width": "0",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "transparent",
      "--pd-preview-h2-border-color": "transparent",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "#616161",
      "--pd-preview-blockquote-mark-color": "transparent",
      "--pd-preview-blockquote-background": "#fbf9fd",
      "--pd-preview-blockquote-border-color": "#35b378",
      "--pd-preview-strong-color": "#35b378",
      "--pd-preview-em-color": "#595959",
      "--pd-preview-hr-color": "#35b378",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "14px",
      "--pd-preview-table-border-color": "#d9d9d9",
      "--pd-preview-table-cell-padding": "8px 10px"
    },
    "syntaxTheme": "one-light",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "8px",
      "border": "1px solid #d7efdf",
      "boxShadow": "none",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#f7fcf9"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      "color": "#2f4f3f"
    },
    "inlineCodeStyle": {
      "padding": "0 2px",
      "borderRadius": "5px",
      "border": "none",
      "background": "transparent",
      "color": "#35b378",
      "fontSize": "0.92em",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "customCss": "",
    "builtin": true
  },
  {
    "id": "lanqing",
    "name": "兰青主题",
    "description": "蓝青线框风格，层次清晰",
    "variables": {
      "--pd-preview-padding": "30px",
      "--pd-preview-font-family": "Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "#3e3e3e",
      "--pd-preview-link-color": "#009688",
      "--pd-preview-inline-code-color": "#009688",
      "--pd-preview-font-size": "16px",
      "--pd-preview-line-height": "26px",
      "--pd-preview-word-spacing": "3px",
      "--pd-preview-letter-spacing": "0.02em",
      "--pd-preview-paragraph-margin-top": "5px",
      "--pd-preview-paragraph-margin-bottom": "5px",
      "--pd-preview-paragraph-indent": "0.85em",
      "--pd-preview-title-color": "#009688",
      "--pd-preview-h1-font-size": "1.8em",
      "--pd-preview-h2-font-size": "1.5em",
      "--pd-preview-h3-font-size": "1.25em",
      "--pd-preview-h4-font-size": "1.2em",
      "--pd-preview-h5-font-size": "1.1em",
      "--pd-preview-h6-font-size": "1em",
      "--pd-preview-h1-color": "#009688",
      "--pd-preview-h2-color": "#009688",
      "--pd-preview-h3-color": "#3e3e3e",
      "--pd-preview-h4-color": "#3e3e3e",
      "--pd-preview-h5-color": "#3e3e3e",
      "--pd-preview-h6-color": "#3e3e3e",
      "--pd-preview-h1-border-width": "1px",
      "--pd-preview-h2-border-width": "0",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "#009688",
      "--pd-preview-h2-border-color": "transparent",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "#777777",
      "--pd-preview-blockquote-mark-color": "transparent",
      "--pd-preview-blockquote-background": "rgba(0, 0, 0, 0.05)",
      "--pd-preview-blockquote-border-color": "#888888",
      "--pd-preview-strong-color": "#3e3e3e",
      "--pd-preview-em-color": "#3e3e3e",
      "--pd-preview-hr-color": "#3e3e3e",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "14px",
      "--pd-preview-table-border-color": "#009688",
      "--pd-preview-table-cell-padding": "8px 10px"
    },
    "syntaxTheme": "one-light",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "8px",
      "border": "1px solid #b2dfdb",
      "boxShadow": "none",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#f3fbfa"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      "color": "#245f5b"
    },
    "inlineCodeStyle": {
      "padding": "0 2px",
      "borderRadius": "5px",
      "border": "none",
      "background": "transparent",
      "color": "#009688",
      "fontSize": "0.92em",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "customCss": "",
    "builtin": true
  },
  {
    "id": "orange-heart",
    "name": "橙心主题",
    "description": "暖橙强调标题与重点信息",
    "variables": {
      "--pd-preview-padding": "30px",
      "--pd-preview-font-family": "Google Sans Code,Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif",
      "--pd-preview-text-color": "#3e3e3e",
      "--pd-preview-link-color": "rgb(239, 112, 96)",
      "--pd-preview-inline-code-color": "rgb(239, 112, 96)",
      "--pd-preview-font-size": "16px",
      "--pd-preview-line-height": "26px",
      "--pd-preview-word-spacing": "3px",
      "--pd-preview-letter-spacing": "0.02em",
      "--pd-preview-paragraph-margin-top": "5px",
      "--pd-preview-paragraph-margin-bottom": "5px",
      "--pd-preview-paragraph-indent": "0.8em",
      "--pd-preview-title-color": "#3e3e3e",
      "--pd-preview-h1-font-size": "2em",
      "--pd-preview-h2-font-size": "1.3em",
      "--pd-preview-h3-font-size": "1.25em",
      "--pd-preview-h4-font-size": "1.05em",
      "--pd-preview-h5-font-size": "0.95em",
      "--pd-preview-h6-font-size": "0.88em",
      "--pd-preview-h1-color": "#3e3e3e",
      "--pd-preview-h2-color": "rgb(239, 112, 96)",
      "--pd-preview-h3-color": "#3e3e3e",
      "--pd-preview-h4-color": "#3e3e3e",
      "--pd-preview-h5-color": "#3e3e3e",
      "--pd-preview-h6-color": "#3e3e3e",
      "--pd-preview-h1-border-width": "0",
      "--pd-preview-h2-border-width": "2px",
      "--pd-preview-h3-border-width": "0",
      "--pd-preview-h4-border-width": "0",
      "--pd-preview-h5-border-width": "0",
      "--pd-preview-h6-border-width": "0",
      "--pd-preview-h1-border-color": "transparent",
      "--pd-preview-h2-border-color": "rgb(239, 112, 96)",
      "--pd-preview-h3-border-color": "transparent",
      "--pd-preview-h4-border-color": "transparent",
      "--pd-preview-h5-border-color": "transparent",
      "--pd-preview-h6-border-color": "transparent",
      "--pd-preview-blockquote-text-color": "#666666",
      "--pd-preview-blockquote-mark-color": "transparent",
      "--pd-preview-blockquote-background": "#fff9f9",
      "--pd-preview-blockquote-border-color": "rgb(239, 112, 96)",
      "--pd-preview-strong-color": "#3e3e3e",
      "--pd-preview-em-color": "#3e3e3e",
      "--pd-preview-hr-color": "#d4d4d4",
      "--pd-preview-image-width": "auto",
      "--pd-preview-table-font-size": "14px",
      "--pd-preview-table-border-color": "#d9d9d9",
      "--pd-preview-table-cell-padding": "8px 10px"
    },
    "syntaxTheme": "one-light",
    "codeBlockStyle": {
      "margin": "16px 0",
      "padding": "14px 16px",
      "borderRadius": "8px",
      "border": "1px solid #ffd7d2",
      "boxShadow": "none",
      "overflowX": "auto",
      "fontSize": "13px",
      "lineHeight": 1.65,
      "background": "#fff9f8"
    },
    "codeBlockCodeStyle": {
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      "color": "#4a3b39"
    },
    "inlineCodeStyle": {
      "padding": "0 2px",
      "borderRadius": "5px",
      "border": "none",
      "background": "transparent",
      "color": "rgb(239, 112, 96)",
      "fontSize": "0.92em",
      "fontFamily": "\"Google Sans Code\",\"Operator Mono\",\"SFMono-Regular\", Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace"
    },
    "customCss": "",
    "builtin": true
  }
];
