COMMENT ON TABLE users IS '用户主表：存储账号基础信息与用户状态';
COMMENT ON COLUMN users.id IS '主键ID';
COMMENT ON COLUMN users.user_id IS '用户业务ID（ULID）';
COMMENT ON COLUMN users.email IS '用户邮箱（全局唯一）';
COMMENT ON COLUMN users.password_hash IS '密码哈希（bcrypt）';
COMMENT ON COLUMN users.name IS '用户显示名称';
COMMENT ON COLUMN users.avatar_url IS '头像URL';
COMMENT ON COLUMN users.status IS '用户状态：active/banned/deleted';
COMMENT ON COLUMN users.banned_reason IS '封禁原因';
COMMENT ON COLUMN users.banned_at IS '封禁时间';
COMMENT ON COLUMN users.deleted_at IS '逻辑删除时间';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.updated_at IS '更新时间';

COMMENT ON TABLE spaces IS '知识空间表：协作内容的顶层容器';
COMMENT ON COLUMN spaces.id IS '主键ID';
COMMENT ON COLUMN spaces.space_id IS '空间业务ID（ULID）';
COMMENT ON COLUMN spaces.name IS '空间名称';
COMMENT ON COLUMN spaces.owner_user_id IS '空间所有者用户ID';
COMMENT ON COLUMN spaces.visibility IS '空间可见性：public/authenticated/member';
COMMENT ON COLUMN spaces.status IS '空间状态：active/banned/deleted';
COMMENT ON COLUMN spaces.banned_reason IS '空间封禁原因';
COMMENT ON COLUMN spaces.banned_at IS '空间封禁时间';
COMMENT ON COLUMN spaces.deleted_at IS '空间逻辑删除时间';
COMMENT ON COLUMN spaces.description IS '空间描述';
COMMENT ON COLUMN spaces.cover_asset_id IS '封面素材ID（关联 space_cover_assets.asset_id）';
COMMENT ON COLUMN spaces.cover_key IS '封面对象存储键';
COMMENT ON COLUMN spaces.cover_url IS '封面访问URL';
COMMENT ON COLUMN spaces.cover_width IS '封面宽度（像素）';
COMMENT ON COLUMN spaces.cover_height IS '封面高度（像素）';
COMMENT ON COLUMN spaces.cover_source IS '封面来源：空/用户上传/系统生成';
COMMENT ON COLUMN spaces.category IS '空间分类名称（兼容旧字段）';
COMMENT ON COLUMN spaces.category_id IS '空间分类ID（关联 space_categories.category_id）';
COMMENT ON COLUMN spaces.created_at IS '创建时间';
COMMENT ON COLUMN spaces.updated_at IS '更新时间';

COMMENT ON TABLE space_members IS '空间成员关系表：定义用户在空间中的协作角色';
COMMENT ON COLUMN space_members.id IS '主键ID';
COMMENT ON COLUMN space_members.space_id IS '空间业务ID';
COMMENT ON COLUMN space_members.user_id IS '用户业务ID';
COMMENT ON COLUMN space_members.role IS '空间角色：owner/collaborator/reader';
COMMENT ON COLUMN space_members.created_at IS '创建时间';
COMMENT ON COLUMN space_members.updated_at IS '更新时间';

COMMENT ON TABLE nodes IS '目录树节点表：空间内目录与文档节点';
COMMENT ON COLUMN nodes.id IS '主键ID';
COMMENT ON COLUMN nodes.node_id IS '节点业务ID（ULID）';
COMMENT ON COLUMN nodes.space_id IS '所属空间ID';
COMMENT ON COLUMN nodes.parent_node_id IS '父节点ID，空表示根节点';
COMMENT ON COLUMN nodes.type IS '节点类型：folder/doc';
COMMENT ON COLUMN nodes.title IS '节点标题';
COMMENT ON COLUMN nodes.sort IS '同级排序值';
COMMENT ON COLUMN nodes.created_by_user_id IS '节点创建人用户ID';
COMMENT ON COLUMN nodes.updated_by_user_id IS '节点最后更新人用户ID';
COMMENT ON COLUMN nodes.created_at IS '创建时间';
COMMENT ON COLUMN nodes.updated_at IS '更新时间';

COMMENT ON TABLE themes IS '文档主题表：存储主题样式与代码高亮配置';
COMMENT ON COLUMN themes.id IS '主键ID';
COMMENT ON COLUMN themes.theme_id IS '主题业务ID';
COMMENT ON COLUMN themes.name IS '主题名称';
COMMENT ON COLUMN themes.description IS '主题描述';
COMMENT ON COLUMN themes.variables_json IS 'CSS 变量JSON';
COMMENT ON COLUMN themes.syntax_theme IS '代码高亮主题：one-light/one-dark';
COMMENT ON COLUMN themes.code_block_style_json IS '代码块容器样式JSON';
COMMENT ON COLUMN themes.code_block_code_style_json IS '代码块代码样式JSON';
COMMENT ON COLUMN themes.inline_code_style_json IS '行内代码样式JSON';
COMMENT ON COLUMN themes.custom_css IS '自定义CSS';
COMMENT ON COLUMN themes.is_builtin IS '是否内置主题';
COMMENT ON COLUMN themes.is_enabled IS '是否启用';
COMMENT ON COLUMN themes.created_at IS '创建时间';
COMMENT ON COLUMN themes.updated_at IS '更新时间';

COMMENT ON TABLE documents IS '文档主表：节点对应的正文与可见性状态';
COMMENT ON COLUMN documents.id IS '主键ID';
COMMENT ON COLUMN documents.document_id IS '文档业务ID（ULID）';
COMMENT ON COLUMN documents.node_id IS '关联节点ID（唯一）';
COMMENT ON COLUMN documents.theme_id IS '主题ID';
COMMENT ON COLUMN documents.title IS '文档标题';
COMMENT ON COLUMN documents.content_md IS 'Markdown 正文';
COMMENT ON COLUMN documents.version IS '文档版本号（乐观锁）';
COMMENT ON COLUMN documents.updated_by_user_id IS '最后更新人用户ID';
COMMENT ON COLUMN documents.visibility IS '文档可见性：public/authenticated/member';
COMMENT ON COLUMN documents.status IS '文档状态：active/banned/deleted';
COMMENT ON COLUMN documents.banned_reason IS '文档封禁原因';
COMMENT ON COLUMN documents.banned_at IS '文档封禁时间';
COMMENT ON COLUMN documents.deleted_at IS '文档逻辑删除时间';
COMMENT ON COLUMN documents.created_by_user_id IS '文档创建人用户ID';
COMMENT ON COLUMN documents.created_at IS '创建时间';
COMMENT ON COLUMN documents.updated_at IS '更新时间';

COMMENT ON TABLE document_revisions IS '文档修订历史表：保存版本快照与来源';
COMMENT ON COLUMN document_revisions.id IS '主键ID';
COMMENT ON COLUMN document_revisions.document_revision_id IS '修订业务ID（ULID）';
COMMENT ON COLUMN document_revisions.document_id IS '文档业务ID';
COMMENT ON COLUMN document_revisions.version IS '修订版本号';
COMMENT ON COLUMN document_revisions.content_md IS '该版本 Markdown 内容';
COMMENT ON COLUMN document_revisions.base_version IS '保存时基准版本号';
COMMENT ON COLUMN document_revisions.editor_user_id IS '编辑人用户ID';
COMMENT ON COLUMN document_revisions.source IS '修订来源：local/remote';
COMMENT ON COLUMN document_revisions.created_at IS '创建时间';

COMMENT ON TABLE node_permissions IS '节点权限表：节点级 ACL 授权关系';
COMMENT ON COLUMN node_permissions.id IS '主键ID';
COMMENT ON COLUMN node_permissions.node_id IS '节点业务ID';
COMMENT ON COLUMN node_permissions.user_id IS '被授权用户ID';
COMMENT ON COLUMN node_permissions.role IS '授权角色：owner/collaborator/reader';
COMMENT ON COLUMN node_permissions.granted_by_user_id IS '授权人用户ID';
COMMENT ON COLUMN node_permissions.created_at IS '创建时间';
COMMENT ON COLUMN node_permissions.updated_at IS '更新时间';

COMMENT ON TABLE document_permissions IS '文档权限表：文档级 ACL 授权关系';
COMMENT ON COLUMN document_permissions.id IS '主键ID';
COMMENT ON COLUMN document_permissions.document_id IS '文档业务ID';
COMMENT ON COLUMN document_permissions.user_id IS '被授权用户ID';
COMMENT ON COLUMN document_permissions.role IS '授权角色：owner/collaborator/reader';
COMMENT ON COLUMN document_permissions.granted_by_user_id IS '授权人用户ID';
COMMENT ON COLUMN document_permissions.created_at IS '创建时间';
COMMENT ON COLUMN document_permissions.updated_at IS '更新时间';

COMMENT ON TABLE user_sessions IS '用户会话表：refresh token 会话状态与轮换链';
COMMENT ON COLUMN user_sessions.id IS '主键ID';
COMMENT ON COLUMN user_sessions.session_id IS '会话业务ID（ULID）';
COMMENT ON COLUMN user_sessions.user_id IS '用户业务ID';
COMMENT ON COLUMN user_sessions.refresh_token_hash IS 'refresh token 哈希';
COMMENT ON COLUMN user_sessions.expires_at IS '会话过期时间';
COMMENT ON COLUMN user_sessions.revoked_at IS '会话吊销时间';
COMMENT ON COLUMN user_sessions.replaced_by_session_id IS '被旋转后替换的新会话ID';
COMMENT ON COLUMN user_sessions.created_at IS '创建时间';
COMMENT ON COLUMN user_sessions.updated_at IS '更新时间';

COMMENT ON TABLE user_admin_roles IS '管理员角色表：绑定平台级管理员角色';
COMMENT ON COLUMN user_admin_roles.id IS '主键ID';
COMMENT ON COLUMN user_admin_roles.user_id IS '用户业务ID';
COMMENT ON COLUMN user_admin_roles.role IS '管理员角色：platform_admin/space_admin';
COMMENT ON COLUMN user_admin_roles.created_at IS '创建时间';
COMMENT ON COLUMN user_admin_roles.updated_at IS '更新时间';

COMMENT ON TABLE space_admin_scopes IS '空间管理员范围表：约束 space_admin 可管理的空间';
COMMENT ON COLUMN space_admin_scopes.id IS '主键ID';
COMMENT ON COLUMN space_admin_scopes.user_id IS '管理员用户ID';
COMMENT ON COLUMN space_admin_scopes.space_id IS '可管理空间ID';
COMMENT ON COLUMN space_admin_scopes.created_at IS '创建时间';
COMMENT ON COLUMN space_admin_scopes.updated_at IS '更新时间';

COMMENT ON TABLE system_configs IS '系统配置中心表：按 config_key 存储 JSON 配置与版本';
COMMENT ON COLUMN system_configs.id IS '主键ID';
COMMENT ON COLUMN system_configs.config_key IS '配置键（唯一）';
COMMENT ON COLUMN system_configs.config_value_json IS '配置值JSON';
COMMENT ON COLUMN system_configs.version IS '配置版本号（从 1 递增）';
COMMENT ON COLUMN system_configs.updated_by_user_id IS '最后更新人用户ID';
COMMENT ON COLUMN system_configs.created_at IS '创建时间';
COMMENT ON COLUMN system_configs.updated_at IS '更新时间';

COMMENT ON TABLE audit_logs IS '后台审计日志表：记录管理端关键操作轨迹';
COMMENT ON COLUMN audit_logs.id IS '主键ID';
COMMENT ON COLUMN audit_logs.actor_user_id IS '操作者用户ID';
COMMENT ON COLUMN audit_logs.module IS '操作模块';
COMMENT ON COLUMN audit_logs.action IS '操作动作';
COMMENT ON COLUMN audit_logs.target_type IS '目标资源类型';
COMMENT ON COLUMN audit_logs.target_id IS '目标资源ID';
COMMENT ON COLUMN audit_logs.summary IS '操作摘要';
COMMENT ON COLUMN audit_logs.detail_json IS '操作详情JSON';
COMMENT ON COLUMN audit_logs.request_id IS '请求链路ID';
COMMENT ON COLUMN audit_logs.created_at IS '创建时间';

COMMENT ON TABLE space_cover_assets IS '空间封面素材表：记录封面源文件元数据';
COMMENT ON COLUMN space_cover_assets.id IS '主键ID';
COMMENT ON COLUMN space_cover_assets.asset_id IS '素材业务ID（ULID）';
COMMENT ON COLUMN space_cover_assets.source IS '素材来源：user_upload/system_generated';
COMMENT ON COLUMN space_cover_assets.object_key IS '对象存储键';
COMMENT ON COLUMN space_cover_assets.object_url IS '对象访问URL';
COMMENT ON COLUMN space_cover_assets.mime_type IS '文件MIME类型';
COMMENT ON COLUMN space_cover_assets.width IS '图片宽度（像素）';
COMMENT ON COLUMN space_cover_assets.height IS '图片高度（像素）';
COMMENT ON COLUMN space_cover_assets.size_bytes IS '文件字节大小';
COMMENT ON COLUMN space_cover_assets.normalized IS '是否已完成尺寸与格式归一化';
COMMENT ON COLUMN space_cover_assets.created_by_user_id IS '创建人用户ID';
COMMENT ON COLUMN space_cover_assets.created_at IS '创建时间';
COMMENT ON COLUMN space_cover_assets.updated_at IS '更新时间';

COMMENT ON TABLE space_categories IS '空间分类表：管理空间归类维度';
COMMENT ON COLUMN space_categories.id IS '主键ID';
COMMENT ON COLUMN space_categories.category_id IS '分类业务ID（ULID）';
COMMENT ON COLUMN space_categories.name IS '分类名称';
COMMENT ON COLUMN space_categories.is_default IS '是否默认分类';
COMMENT ON COLUMN space_categories.created_at IS '创建时间';
COMMENT ON COLUMN space_categories.updated_at IS '更新时间';

COMMENT ON TABLE user_identities IS '用户身份映射表：关联本地账号与外部身份提供方';
COMMENT ON COLUMN user_identities.id IS '主键ID';
COMMENT ON COLUMN user_identities.user_id IS '用户业务ID';
COMMENT ON COLUMN user_identities.provider_type IS '身份提供方类型，如 local/ldap';
COMMENT ON COLUMN user_identities.provider_id IS '身份提供方实例ID';
COMMENT ON COLUMN user_identities.external_id IS '外部身份唯一标识';
COMMENT ON COLUMN user_identities.login_name IS '用于登录展示或匹配的名称';
COMMENT ON COLUMN user_identities.last_login_at IS '最近一次登录时间';
COMMENT ON COLUMN user_identities.created_at IS '创建时间';
COMMENT ON COLUMN user_identities.updated_at IS '更新时间';
